# This is the main config. Parameters are update and possibly overwritten by dataset dependent configs.
model:
  mode: train # "train", "test", "predict", "predict_features"
  batch_size: 16
  epochs: 40
  learning_rate: 0.01
  optimizer: sgd
  class_weighted_loss: True
  use_fixed_class_weights: False
  loss_function: categorical_crossentropy # "categorical_crossentropy", "focal_loss"
  load_name: None
  save_name: efficientnetb1
  feature_extractor:
    type: efficientnetb1 # "fsconv", "simple_cnn", "mobilenetv2", "resnet50", "efficientnetb0", "efficientnetb1"
    global_max_pooling: False
    num_output_features: 8 # feature dimension of feature extractor output, set to 0 to skip this layer
    output_activation: sigmoid # sigmoid, relu
  head:
    type: deterministic # deterministic, gp, bnn
    deterministic:
      dropout: 0.2
      number_hidden_units: 0 # feature dimension of hidden layer, set to 0 to skip this layer
    gp:
      inducing_points: 200
    bnn:
      number_hidden_units: 100
      kl_loss_factor: 1

data:
  dataset_config: ./dataset_dependent/sicapv2/config.yaml
  supervision: mil # 'full', 'mil'
  positive_instance_labels_per_bag: 10
  positive_pseudo_instance_labels_per_bag: 10
  strong_augment_brightness_range: [0.5, 2.0]
  strong_augment_channel_shift: 0.0
  weak_augment_brightness_range: [0.9, 1.1]
  weak_augment_channel_shift: 0.0
  label_weights:
    positive_gt_labels: 2.0
    pseudo_labels: 2.0
    soft_labels: 1.0
    negative_gt_labels: 0.5

logging:
  log_experiment: True
  run_name: efficientnetb1
  tracking_url: /home/arne/projects/mlruns