data:
  dataset_name: sicapv2
  dir: /home/arne/datasets/SICAPv2/
#  data_split_dir: /home/arne/datasets/SICAPv2/partition/Validation/Val1/
  data_split_dir: /home/arne/projects/cancer_classification/dev_branch2/cancer_classification/dataset_dependent/sicapv2/dummy_dataset
#  dir: /data/SICAPv2/images/
#  data_split_dir: /data/SICAPv2/partition/Validation/Val1
  artifact_dir: ./dataset_dependent/sicapv2
  image_target_size: [250, 250]
  num_classes: 4
  mil_class_weights:
    0: 0.1
    1: 0.3
    2: 0.3
    3: 0.3



