data:
  dataset_name: sicapv2
  dir: /home/arne/datasets/SICAPv2_add_wsi/
  data_split_dir: /home/arne/projects/cancer_classification/dev_branch2/cancer_classification/dataset_dependent/sicapv2/dummy_dataset/mil/
#  data_split_dir: /home/arne/datasets/SICAPv2_add_wsi/partition/Test/
#  dir: /data/BasesDeDatos/SICAP/SICAPv2_MIL/
#  data_split_dir: /data/BasesDeDatos/SICAP/SICAPv2_MIL/partition_mil/Validation/Val1
  artifact_dir: ./dataset_dependent/sicapv2/
  image_target_size: [250, 250]
  num_classes: 4
  data_type: prostate_cancer



