data:
  dataset_name: camelyon16
  dir: /path/to/cam16
  data_split_dir: /path/to/cam16
  artifact_dir: ./dataset_dependent/camelyon16/
  image_target_size: [250, 250]
  num_classes: 2
  dataset_type: cancer_binary


