data:
  dataset_name: camelyon16
  dir: /work/Camelyon16_MIL/sensitive/
  data_split_dir: /work/Camelyon16_MIL/sensitive/
  artifact_dir: ./dataset_dependent/camelyon16/
  image_target_size: [250, 250]
  num_classes: 2
  dataset_type: cancer_binary


