data:
  dataset_name: panda
  dir: /home/arne/datasets/Panda/Panda_patches
  data_split_dir: dataset_dependent/panda/dummy_dataset/
#  dir: /data/BasesDeDatos/Panda/Panda_patches
#  data_split_dir: /data/BasesDeDatos/Panda/Panda_patches
  artifact_dir: ./dataset_dependent/panda/
  image_target_size: [250, 250]
  num_classes: 4
  data_type: prostate_cancer


